import 'package:flutter/material.dart';

/* UndefinedNode Event Card 6
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedEventCard6Widget3 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(child: Container());
  }
}
