import 'package:flutter/material.dart';

/* UndefinedNode Individual Interests
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedIndividualInterestsWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(child: Container());
  }
}
