import 'package:flutter/material.dart';

/* UndefinedNode user profile pic
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedUserprofilepicWidget11 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(child: Container());
  }
}
