import 'package:flutter/material.dart';

/* UndefinedNode Event Card 7
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedEventCard7Widget3 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(child: Container());
  }
}
