import 'package:flutter/material.dart';

/* UndefinedNode _Circle Buttons
    Autogenerated by FlutLab FTF Generator
  */
class Generated_CircleButtonsWidget9 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(child: Container());
  }
}
