import 'package:flutter/material.dart';

/* UndefinedNode Edit Icon
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedEditIconWidget2 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(child: Container());
  }
}
