import 'package:flutter/material.dart';

/* UndefinedNode red book mark
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedRedbookmarkWidget5 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(child: Container());
  }
}
