import 'package:flutter/material.dart';

/* UndefinedNode Checkboxes
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedCheckboxesWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(child: Container());
  }
}
