import 'package:flutter/material.dart';

/* UndefinedNode Edit Icon Grey 
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedEditIconGreyWidget10 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(child: Container());
  }
}
