import 'package:flutter/material.dart';

/* UndefinedNode Event Icons
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedEventIconsWidget48 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(child: Container());
  }
}
