import 'package:flutter/material.dart';

/* UndefinedNode Select Event Type
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedSelectEventTypeWidget2 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(child: Container());
  }
}
