import 'package:flutter/material.dart';

/* UndefinedNode Bottom Button
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedBottomButtonWidget36 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(child: Container());
  }
}
