import 'package:flutter/material.dart';

/* UndefinedNode Event Card 2
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedEventCard2Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(child: Container());
  }
}
