import 'package:flutter/material.dart';

/* UndefinedNode Event Card 1
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedEventCard1Widget2 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(child: Container());
  }
}
