import 'package:flutter/material.dart';

/* UndefinedNode Type Badges
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedTypeBadgesWidget5 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(child: Container());
  }
}
