import 'package:flutter/material.dart';

/* UndefinedNode Input chip
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedInputchipWidget9 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(child: Container());
  }
}
