import 'package:flutter/material.dart';

/* UndefinedNode List
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedListWidget22 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(child: Container());
  }
}
