import 'package:flutter/material.dart';

/* UndefinedNode Event Card 3
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedEventCard3Widget1 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(child: Container());
  }
}
