import 'package:flutter/material.dart';

/* UndefinedNode Members dropdown
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedMembersdropdownWidget6 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(child: Container());
  }
}
