import 'package:flutter/material.dart';

/* UndefinedNode Bottom buttons and rectangle
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedBottombuttonsandrectangleWidget9 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(child: Container());
  }
}
