import 'package:flutter/material.dart';
import 'package:flutterapp/undigitally_20frontendapp/generatedpeoplesuggestionwidget/generated/GeneratedSuggestion4Widget.dart';
import 'package:flutterapp/undigitally_20frontendapp/generatedpeoplesuggestionwidget/generated/GeneratedSuggestion1Widget.dart';
import 'package:flutterapp/undigitally_20frontendapp/generatedpeoplesuggestionwidget/generated/GeneratedSuggestion2Widget.dart';
import 'package:flutterapp/undigitally_20frontendapp/generatedpeoplesuggestionwidget/generated/GeneratedSuggestion5Widget.dart';
import 'package:flutterapp/undigitally_20frontendapp/generatedpeoplesuggestionwidget/generated/GeneratedSuggestion6Widget.dart';
import 'package:flutterapp/undigitally_20frontendapp/generatedpeoplesuggestionwidget/generated/GeneratedSuggestion3Widget.dart';

/* Component People Suggestion
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedPeopleSuggestionWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(child: LayoutBuilder(
        builder: (BuildContext context, BoxConstraints constraints) {
      return SingleChildScrollView(
        scrollDirection: Axis.horizontal,
        child: Container(
            width: 849.0,
            child: Stack(children: [
              Container(
                  height: constraints.maxHeight,
                  child: Container(
                    width: 849.0,
                    height: 143.0,
                    child: Stack(
                        fit: StackFit.expand,
                        alignment: Alignment.center,
                        clipBehavior: Clip.none,
                        children: [
                          Positioned(
                            left: 15.0,
                            top: 0.0,
                            right: null,
                            bottom: null,
                            width: 110.0,
                            height: 143.0,
                            child: GeneratedSuggestion1Widget(),
                          ),
                          Positioned(
                            left: 156.0,
                            top: 0.0,
                            right: null,
                            bottom: null,
                            width: 110.0,
                            height: 143.0,
                            child: GeneratedSuggestion2Widget(),
                          ),
                          Positioned(
                            left: 297.0,
                            top: 0.0,
                            right: null,
                            bottom: null,
                            width: 110.0,
                            height: 143.0,
                            child: GeneratedSuggestion3Widget(),
                          ),
                          Positioned(
                            left: 438.0,
                            top: 0.0,
                            right: null,
                            bottom: null,
                            width: 114.0,
                            height: 143.0,
                            child: GeneratedSuggestion4Widget(),
                          ),
                          Positioned(
                            left: 583.0,
                            top: 0.0,
                            right: null,
                            bottom: null,
                            width: 110.0,
                            height: 143.0,
                            child: GeneratedSuggestion5Widget(),
                          ),
                          Positioned(
                            left: 724.0,
                            top: 0.0,
                            right: null,
                            bottom: null,
                            width: 110.0,
                            height: 143.0,
                            child: GeneratedSuggestion6Widget(),
                          )
                        ]),
                  ))
            ])),
      );
    }));
  }
}
