import 'package:flutter/material.dart';
import 'package:flutterapp/undigitally_20frontendapp/generatedcolourpalletewidget/generated/GeneratedFrame23Widget.dart';
import 'package:flutterapp/undigitally_20frontendapp/generatedcolourpalletewidget/generated/GeneratedFrame19Widget.dart';
import 'package:flutterapp/undigitally_20frontendapp/generatedcolourpalletewidget/generated/GeneratedFrame21Widget.dart';
import 'package:flutterapp/undigitally_20frontendapp/generatedcolourpalletewidget/generated/GeneratedRectangle32Widget.dart';
import 'package:flutterapp/undigitally_20frontendapp/generatedcolourpalletewidget/generated/GeneratedFrame17Widget.dart';
import 'package:flutterapp/undigitally_20frontendapp/generatedcolourpalletewidget/generated/GeneratedFrame18Widget.dart';
import 'package:flutterapp/undigitally_20frontendapp/generatedcolourpalletewidget/generated/GeneratedFrame20Widget.dart';
import 'package:flutterapp/undigitally_20frontendapp/generatedcolourpalletewidget/generated/GeneratedFrame14Widget.dart';
import 'package:flutterapp/undigitally_20frontendapp/generatedcolourpalletewidget/generated/GeneratedFrame16Widget.dart';
import 'package:flutterapp/undigitally_20frontendapp/generatedcolourpalletewidget/generated/GeneratedFrame22Widget.dart';
import 'package:flutterapp/undigitally_20frontendapp/generatedcolourpalletewidget/generated/GeneratedFrame15Widget.dart';

/* Component colour pallete
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedColourpalleteWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: Container(
      width: 896.0,
      height: 130.0,
      child: Stack(
          fit: StackFit.expand,
          alignment: Alignment.center,
          clipBehavior: Clip.none,
          children: [
            Positioned(
              left: 0.0,
              top: 0.0,
              right: null,
              bottom: null,
              width: 23.0,
              height: 21.0,
              child: GeneratedRectangle32Widget(),
            ),
            Positioned(
              left: 33.0,
              top: 0.0,
              right: null,
              bottom: null,
              width: 80.0,
              height: 130.0,
              child: GeneratedFrame14Widget(),
            ),
            Positioned(
              left: 123.0,
              top: 0.0,
              right: null,
              bottom: null,
              width: 80.0,
              height: 130.0,
              child: GeneratedFrame15Widget(),
            ),
            Positioned(
              left: 213.0,
              top: 0.0,
              right: null,
              bottom: null,
              width: 80.0,
              height: 130.0,
              child: GeneratedFrame16Widget(),
            ),
            Positioned(
              left: 303.0,
              top: 0.0,
              right: null,
              bottom: null,
              width: 80.0,
              height: 130.0,
              child: GeneratedFrame17Widget(),
            ),
            Positioned(
              left: 393.0,
              top: 0.0,
              right: null,
              bottom: null,
              width: 80.0,
              height: 130.0,
              child: GeneratedFrame18Widget(),
            ),
            Positioned(
              left: 483.0,
              top: 0.0,
              right: null,
              bottom: null,
              width: 80.0,
              height: 130.0,
              child: GeneratedFrame19Widget(),
            ),
            Positioned(
              left: 573.0,
              top: 0.0,
              right: null,
              bottom: null,
              width: 80.0,
              height: 130.0,
              child: GeneratedFrame20Widget(),
            ),
            Positioned(
              left: 663.0,
              top: 0.0,
              right: null,
              bottom: null,
              width: 80.0,
              height: 130.0,
              child: GeneratedFrame21Widget(),
            ),
            Positioned(
              left: 753.0,
              top: 0.0,
              right: null,
              bottom: null,
              width: 80.0,
              height: 130.0,
              child: GeneratedFrame22Widget(),
            ),
            Positioned(
              left: 843.0,
              top: 0.0,
              right: null,
              bottom: null,
              width: 80.0,
              height: 130.0,
              child: GeneratedFrame23Widget(),
            )
          ]),
    ));
  }
}
