import 'package:flutter/material.dart';
import 'package:flutterapp/undigitally_20frontendapp/generatedsignuppagewidget/generated/GeneratedCreateanaccountWidget.dart';
import 'package:flutterapp/undigitally_20frontendapp/generatedsignuppagewidget/generated/GeneratedRectangle29Widget.dart';
import 'package:flutterapp/undigitally_20frontendapp/generatedsignuppagewidget/generated/GeneratedEllipse1Widget1.dart';
import 'package:flutterapp/undigitally_20frontendapp/generatedsignuppagewidget/generated/GeneratedMobileheaderWidget.dart';
import 'package:flutterapp/undigitally_20frontendapp/generatedsignuppagewidget/generated/GeneratedFrame4Widget.dart';
import 'package:flutterapp/undigitally_20frontendapp/generatedsignuppagewidget/generated/GeneratedEllipse1Widget.dart';
import 'package:flutterapp/helpers/transform/transform.dart';
import 'package:flutterapp/undigitally_20frontendapp/generatedsignuppagewidget/generated/GeneratedEllipse2Widget.dart';
import 'package:flutterapp/undigitally_20frontendapp/generatedsignuppagewidget/generated/GeneratedFrame5Widget.dart';

/* Frame Signup Page
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedSignupPageWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 390.0,
        height: 844.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            clipBehavior: Clip.none,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 435.3245544433594,
                top: 943.2649536132812,
                right: null,
                bottom: null,
                width: 899.6814575195312,
                height: 929.4221801757812,
                child: GeneratedRectangle29Widget(),
              ),
              Positioned(
                left: -157.0,
                top: 690.2532958984375,
                right: null,
                bottom: null,
                width: 260.9591064453125,
                height: 273.4522399902344,
                child: GeneratedEllipse1Widget(),
              ),
              Positioned(
                left: 88.0,
                top: 697.602294921875,
                right: null,
                bottom: null,
                width: 364.3127746582031,
                height: 273.4522399902344,
                child: GeneratedEllipse2Widget(),
              ),
              Positioned(
                left: -157.0,
                top: -331.705810546875,
                right: null,
                bottom: null,
                width: 518.3734741210938,
                height: 581.5103759765625,
                child: GeneratedEllipse1Widget1(),
              ),
              Positioned(
                left: 0.0,
                top: null,
                right: 0.0,
                bottom: null,
                width: null,
                height: 73.0,
                child: TransformHelper.translate(
                    x: 0.00, y: -343.50, z: 0, child: GeneratedFrame4Widget()),
              ),
              Positioned(
                left: null,
                top: 117.0,
                right: null,
                bottom: null,
                width: 206.0,
                height: 34.0,
                child: TransformHelper.translate(
                    x: -44.00,
                    y: 0.00,
                    z: 0,
                    child: GeneratedCreateanaccountWidget()),
              ),
              Positioned(
                left: null,
                top: null,
                right: null,
                bottom: null,
                width: 327.0,
                height: 631.5384521484375,
                child: TransformHelper.translate(
                    x: 4.50, y: 54.77, z: 0, child: GeneratedFrame5Widget()),
              ),
              Positioned(
                left: 0.0,
                top: -3.0,
                right: 1.0,
                bottom: null,
                width: null,
                height: 33.0,
                child: GeneratedMobileheaderWidget(),
              )
            ]),
      ),
    ));
  }
}
