import 'package:flutter/material.dart';
import 'package:flutterapp/undigitally_20frontendapp/generatedloginpagewidget/generated/GeneratedAllcomponentbelowemailandpassWidget.dart';
import 'package:flutterapp/undigitally_20frontendapp/generatedloginpagewidget/generated/GeneratedFrame3Widget.dart';
import 'package:flutterapp/undigitally_20frontendapp/generatedloginpagewidget/generated/GeneratedEllipse1Widget3.dart';
import 'package:flutterapp/undigitally_20frontendapp/generatedloginpagewidget/generated/GeneratedLoginillustrationWidget.dart';
import 'package:flutterapp/undigitally_20frontendapp/generatedloginpagewidget/generated/GeneratedEllipse2Widget1.dart';
import 'package:flutterapp/undigitally_20frontendapp/generatedloginpagewidget/generated/GeneratedMobileheaderWidget1.dart';
import 'package:flutterapp/helpers/transform/transform.dart';
import 'package:flutterapp/undigitally_20frontendapp/generatedloginpagewidget/generated/GeneratedEllipse1Widget2.dart';
import 'package:flutterapp/undigitally_20frontendapp/generatedloginpagewidget/generated/GeneratedRectangle29Widget1.dart';

/* Frame Login Page
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedLoginPageWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 390.0,
        height: 844.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            clipBehavior: Clip.none,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 435.3245544433594,
                top: 943.2649536132812,
                right: null,
                bottom: null,
                width: 899.6814575195312,
                height: 929.4221801757812,
                child: GeneratedRectangle29Widget1(),
              ),
              Positioned(
                left: -157.0,
                top: 690.2532958984375,
                right: null,
                bottom: null,
                width: 260.9591064453125,
                height: 273.4522399902344,
                child: GeneratedEllipse1Widget2(),
              ),
              Positioned(
                left: 88.0,
                top: 697.602294921875,
                right: null,
                bottom: null,
                width: 364.3127746582031,
                height: 273.4522399902344,
                child: GeneratedEllipse2Widget1(),
              ),
              Positioned(
                left: -157.0,
                top: -331.705810546875,
                right: null,
                bottom: null,
                width: 518.3734741210938,
                height: 581.5103759765625,
                child: GeneratedEllipse1Widget3(),
              ),
              Positioned(
                left: null,
                top: 42.0,
                right: null,
                bottom: null,
                width: 389.0,
                height: 73.0,
                child: TransformHelper.translate(
                    x: 0.50, y: 0.00, z: 0, child: GeneratedFrame3Widget()),
              ),
              Positioned(
                left: null,
                top: 117.0,
                right: null,
                bottom: null,
                width: 308.0,
                height: 235.4925537109375,
                child: TransformHelper.translate(
                    x: 10.00,
                    y: 0.00,
                    z: 0,
                    child: GeneratedLoginillustrationWidget()),
              ),
              Positioned(
                left: null,
                top: null,
                right: null,
                bottom: null,
                width: 407.0,
                height: 442.0,
                child: TransformHelper.translate(
                    x: 2.50,
                    y: 156.00,
                    z: 0,
                    child: GeneratedAllcomponentbelowemailandpassWidget()),
              ),
              Positioned(
                left: 1.0,
                top: null,
                right: 0.0,
                bottom: null,
                width: null,
                height: 33.0,
                child: TransformHelper.translate(
                    x: 0.00,
                    y: -405.50,
                    z: 0,
                    child: GeneratedMobileheaderWidget1()),
              )
            ]),
      ),
    ));
  }
}
